import type { ReportLanguage } from '../types/analysis';

export const normalizeReportLanguage = (value?: string | null): ReportLanguage =>
  value === 'en' ? 'en' : 'zh';

const REPORT_TEXT = {
  zh: {
    keyInsights: 'NHẬN ĐỊNH CHÍNH',
    noAnalysisSummary: 'Chưa có kết luận phân tích',
    actionAdvice: 'Khuyến nghị giao dịch',
    noAdvice: 'Chưa có khuyến nghị',
    trendPrediction: 'Dự báo xu hướng',
    noPrediction: 'Chưa có dự báo',
    marketSentiment: 'Tâm lý thị trường',
    strategyPoints: 'ĐIỂM CHIẾN LƯỢC',
    sniperLevels: 'Điểm vào lệnh',
    idealBuy: 'Mua lý tưởng',
    secondaryBuy: 'Mua bổ sung',
    stopLoss: 'Cắt lỗ',
    takeProfit: 'Chốt lời',
    noValue: '—',
    newsFeed: 'TIN TỨC',
    relatedNews: 'Tin liên quan',
    refresh: 'Làm mới',
    retry: 'Thử lại',
    dismiss: 'Đóng',
    details: 'Xem chi tiết',
    loadingNews: 'Đang tải tin tức...',
    noNews: 'Chưa có tin tức liên quan',
    noNewsDescription: 'Làm mới sau để cập nhật tin tức mới nhất.',
    openLink: 'Mở',
    transparency: 'Minh bạch',
    traceability: 'Truy xuất dữ liệu',
    rawResult: 'Kết quả phân tích gốc',
    analysisSnapshot: 'Ảnh chụp phân tích',
    copy: 'Sao chép',
    copied: 'Đã sao chép',
    recordId: 'ID bản ghi',
    fullReport: 'Báo cáo phân tích đầy đủ',
    loadingReport: 'Đang tải báo cáo...',
    loadReportFailed: 'Tải báo cáo thất bại',
    copyMarkdownSource: 'Sao chép mã nguồn Markdown',
    copyPlainText: 'Sao chép văn bản thuần',
    analysisModel: 'Mô hình phân tích',
    fearGreedIndex: 'Chỉ số Sợ hãi & Tham lam',
    boardLinkage: 'LIÊN KẾT NHÓM CỔ PHIẾU',
    relatedBoards: 'Nhóm liên quan',
    leadingBoard: 'Dẫn tăng',
    laggingBoard: 'Dẫn giảm',
    neutralBoard: 'Trung tính',
  },
  en: {
    keyInsights: 'KEY INSIGHTS',
    noAnalysisSummary: 'No analysis summary yet',
    actionAdvice: 'Action Advice',
    noAdvice: 'No advice yet',
    trendPrediction: 'Trend Outlook',
    noPrediction: 'No forecast yet',
    marketSentiment: 'Market Sentiment',
    strategyPoints: 'STRATEGY POINTS',
    sniperLevels: 'Action Levels',
    idealBuy: 'Ideal Entry',
    secondaryBuy: 'Secondary Entry',
    stopLoss: 'Stop Loss',
    takeProfit: 'Take Profit',
    noValue: '—',
    newsFeed: 'NEWS FEED',
    relatedNews: 'Related News',
    refresh: 'Refresh',
    retry: 'Retry',
    dismiss: 'Close',
    details: 'View details',
    loadingNews: 'Loading news...',
    noNews: 'No related news',
    noNewsDescription: 'Refresh later to check for the latest updates.',
    openLink: 'Open',
    transparency: 'TRANSPARENCY',
    traceability: 'Data Traceability',
    rawResult: 'Raw Analysis Result',
    analysisSnapshot: 'Analysis Snapshot',
    copy: 'Copy',
    copied: 'Copied!',
    recordId: 'Record ID',
    fullReport: 'Full Analysis Report',
    loadingReport: 'Loading report...',
    loadReportFailed: 'Failed to load report',
    copyMarkdownSource: 'Copy Markdown Source',
    copyPlainText: 'Copy Plain Text',
    analysisModel: 'Model',
    fearGreedIndex: 'Fear & Greed Index',
    boardLinkage: 'BOARD LINKAGE',
    relatedBoards: 'Related Boards',
    leadingBoard: 'Leading',
    laggingBoard: 'Lagging',
    neutralBoard: 'Neutral',
  },
} as const;

export const getReportText = (language?: string | null) => REPORT_TEXT[normalizeReportLanguage(language)];
